compilers:
  - family: gcc
    versions: [13, 14]
  - family: clang
    versions: [17, 18]

optimization_levels:
  - "-O0"
  - "-O1"
  - "-O2"
  - "-O3"
  - "-Os"

isas:
  - name: x86_64
    chost: x86_64-pc-linux-gnu

  - name: aarch64
    chost: aarch64-unknown-linux-gnu

  - name: mipsel
    chost: mipsel-unknown-linux-gnu
