packages:
  - name: zlib
    version: "1.3.1"
    source:
      type: tarball
      url: "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz"
    build_system: cmake
    build_options:
      cmake_args: []

  - name: coreutils
    version: "9.5"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/coreutils/coreutils-9.5.tar.xz"
    build_system: autotools
    build_options: {}

  - name: openssl
    version: "3.3.1"
    source:
      type: tarball
      url: "https://github.com/openssl/openssl/releases/download/openssl-3.3.1/openssl-3.3.1.tar.gz"
    build_system: custom
    build_options:
      configure_cmd: "./Configure {OPENSSL_TARGET} --cross-compile-prefix={CROSS_PREFIX} CC={CC} CFLAGS=\"{CFLAGS}\" no-shared no-tests"
      build_cmd: "make -j$(nproc)"

  - name: busybox
    version: "1.36.1"
    source:
      type: tarball
      url: "https://busybox.net/downloads/busybox-1.36.1.tar.bz2"
    build_system: custom
    build_options:
      configure_cmd: "make defconfig"
      build_cmd: "make -j$(nproc) CC={CC} CFLAGS=\"{CFLAGS}\" CROSS_COMPILE={CROSS_PREFIX}"

  - name: binutils
    version: "2.42"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.xz"
    build_system: autotools
    build_options:
      configure_args:
        - "--disable-nls"
        - "--disable-werror"
