packages:
  - name: zlib
    version: "1.3.1"
    source:
      type: tarball
      url: "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz"
    build_system: cmake
    build_options:
      cmake_args: []

  - name: coreutils
    version: "9.5"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/coreutils/coreutils-9.5.tar.xz"
    build_system: autotools
    build_options: {}

  - name: openssl
    version: "3.3.1"
    source:
      type: tarball
      url: "https://github.com/openssl/openssl/releases/download/openssl-3.3.1/openssl-3.3.1.tar.gz"
    build_system: custom
    build_options:
      configure_cmd: "./Configure {OPENSSL_TARGET} --cross-compile-prefix={CROSS_PREFIX} CC={CC} CFLAGS=\"{CFLAGS}\" no-shared no-tests"
      build_cmd: "make -j$(nproc)"

  - name: busybox
    version: "1.36.1"
    source:
      type: tarball
      url: "https://busybox.net/downloads/busybox-1.36.1.tar.bz2"
    build_system: custom
    build_options:
      configure_cmd: "make defconfig"
      build_cmd: "make -j$(nproc) CC={CC} CFLAGS=\"{CFLAGS}\" CROSS_COMPILE={CROSS_PREFIX}"

  - name: binutils
    version: "2.42"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.xz"
    build_system: autotools
    build_options:
      configure_args:
        - "--disable-nls"
        - "--disable-werror"

  - name: lz4
    version: "1.9.4"
    source:
      type: tarball
      url: "https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz"
    build_system: cmake
    build_options:
      source_subdir: "build/cmake"
      cmake_args:
        - "-DBUILD_SHARED_LIBS=OFF"

  - name: xz-utils
    version: "5.4.5"
    source:
      type: tarball
      url: "https://github.com/tukaani-project/xz/releases/download/v5.4.5/xz-5.4.5.tar.gz"
    build_system: autotools
    build_options:
      configure_args:
        - "--disable-shared"

  - name: bzip2
    version: "1.0.8"
    source:
      type: tarball
      url: "https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"
    build_system: custom
    build_options:
      configure_cmd: "true"
      build_cmd: "make -j$(nproc) CC={CC} CFLAGS=\"{CFLAGS}\" libbz2.a bzip2"

  - name: curl
    version: "8.5.0"
    source:
      type: tarball
      url: "https://curl.se/download/curl-8.5.0.tar.gz"
    build_system: autotools
    build_options:
      configure_args:
        - "--without-ssl"
        - "--disable-shared"

  - name: libxml2
    version: "2.9.14"
    source:
      type: tarball
      url: "https://download.gnome.org/sources/libxml2/2.9/libxml2-2.9.14.tar.xz"
    build_system: autotools
    build_options:
      configure_args:
        - "--without-python"
        - "--without-icu"
        - "--disable-shared"

  - name: sqlite3
    version: "3.45.1"
    source:
      type: tarball
      url: "https://www.sqlite.org/2024/sqlite-autoconf-3450100.tar.gz"
    build_system: autotools
    build_options:
      configure_args:
        - "--disable-shared"

  - name: libpng
    version: "1.6.43"
    source:
      type: tarball
      url: "https://download.sourceforge.net/libpng/libpng-1.6.43.tar.xz"
    build_system: autotools
    build_options:
      configure_args:
        - "--disable-shared"

  - name: libgcrypt
    version: "1.10.3"
    source:
      type: tarball
      url: "https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.10.3.tar.bz2"
    build_system: autotools
    build_options:
      configure_args:
        - "--disable-shared"
        - "--disable-asm"

  - name: grep
    version: "3.11"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/grep/grep-3.11.tar.xz"
    build_system: autotools
    build_options: {}

  - name: sed
    version: "4.9"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/sed/sed-4.9.tar.xz"
    build_system: autotools
    build_options: {}

  - name: gawk
    version: "5.2.1"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/gawk/gawk-5.2.1.tar.xz"
    build_system: autotools
    build_options: {}

  - name: diffutils
    version: "3.10"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz"
    build_system: autotools
    build_options: {}

  - name: findutils
    version: "4.9.0"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/findutils/findutils-4.9.0.tar.xz"
    build_system: autotools
    build_options: {}

  - name: tar
    version: "1.35"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz"
    build_system: autotools
    build_options: {}

  - name: gzip
    version: "1.12"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/gzip/gzip-1.12.tar.xz"
    build_system: autotools
    build_options: {}

  - name: patch
    version: "2.7.6"
    source:
      type: tarball
      url: "https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz"
    build_system: autotools
    build_options: {}

  - name: less
    version: "590"
    source:
      type: tarball
      url: "https://www.greenwoodsoftware.com/less/less-590.tar.gz"
    build_system: autotools
    build_options:
      configure_args:
        - "--with-regex=posix"
